// Database schema definitions for all tables
export const databaseSchemas = {
    // Supermarket Sales table schema
    supermarket_sales: [
      { field: "invoice_id", description: "A unique code for each purchase.", dataType: "String" },
      { field: "branch", description: "The location of the supermarket branch.", dataType: "String" },
      { field: "city", description: "The city where the supermarket is located.", dataType: "String" },
      { field: "customer_type", description: "The type of customer (e.g., member or normal).", dataType: "String" },
      { field: "gender", description: "The gender of the customer.", dataType: "String" },
      { field: "product_line", description: "The category of product that was sold.", dataType: "String" },
      { field: "unit_price", description: "The price of one item.", dataType: "Number" },
      { field: "quantity", description: "The number of items purchased.", dataType: "Integer" },
      { field: "tax", description: "The amount of tax applied to the sale.", dataType: "Number" },
      { field: "total", description: "The final amount the customer paid.", dataType: "Number" },
      { field: "date", description: "The date of the sale.", dataType: "Date" },
      { field: "time", description: "The time of the sale.", dataType: "Time" },
      { field: "payment", description: "How the customer paid (e.g., cash, credit card).", dataType: "String" },
      { field: "cogs", description: "The cost of goods sold.", dataType: "Number" },
      {
        field: "gross_margin_percentage",
        description: "The percentage of revenue remaining after deducting the cost of goods sold.",
        dataType: "Number",
      },
      {
        field: "gross_income",
        description: "The amount of money earned after deducting the cost of goods sold.",
        dataType: "Number",
      },
      { field: "rating", description: "A customer satisfaction score for the purchase.", dataType: "Number" },
    ],
  
    // Products table schema
    products: [
      { field: "product_id", description: "A unique identifier for each product.", dataType: "String" },
      { field: "product_name", description: "The name of the product.", dataType: "String" },
      { field: "category", description: "The category the product belongs to.", dataType: "String" },
      { field: "sub_category", description: "A more specific category classification.", dataType: "String" },
      { field: "brand", description: "The brand or manufacturer of the product.", dataType: "String" },
      { field: "retail_price", description: "The recommended selling price.", dataType: "Number" },
      {
        field: "wholesale_price",
        description: "The price at which the store purchases the product.",
        dataType: "Number",
      },
      { field: "stock_quantity", description: "The number of units currently in stock.", dataType: "Integer" },
      { field: "reorder_level", description: "The minimum stock level before reordering.", dataType: "Integer" },
      { field: "expiry_date", description: "The date when the product expires (if applicable).", dataType: "Date" },
      { field: "supplier_id", description: "Reference to the supplier of this product.", dataType: "String" },
      { field: "is_active", description: "Whether the product is currently being sold.", dataType: "Boolean" },
    ],
  
    // Customers table schema
    customers: [
      { field: "customer_id", description: "A unique identifier for each customer.", dataType: "String" },
      { field: "first_name", description: "The customer's first name.", dataType: "String" },
      { field: "last_name", description: "The customer's last name.", dataType: "String" },
      { field: "email", description: "The customer's email address.", dataType: "String" },
      { field: "phone", description: "The customer's phone number.", dataType: "String" },
      { field: "address", description: "The customer's street address.", dataType: "String" },
      { field: "city", description: "The city where the customer lives.", dataType: "String" },
      { field: "state", description: "The state where the customer lives.", dataType: "String" },
      { field: "zip_code", description: "The customer's postal code.", dataType: "String" },
      { field: "membership_type", description: "The type of membership the customer has.", dataType: "String" },
      { field: "join_date", description: "The date when the customer joined the membership program.", dataType: "Date" },
      { field: "points", description: "Loyalty points accumulated by the customer.", dataType: "Integer" },
      { field: "birth_date", description: "The customer's date of birth.", dataType: "Date" },
    ],
  
    // Employees table schema
    employees: [
      { field: "employee_id", description: "A unique identifier for each employee.", dataType: "String" },
      { field: "first_name", description: "The employee's first name.", dataType: "String" },
      { field: "last_name", description: "The employee's last name.", dataType: "String" },
      { field: "position", description: "The employee's job title or role.", dataType: "String" },
      { field: "department", description: "The department the employee works in.", dataType: "String" },
      { field: "branch_id", description: "The branch where the employee works.", dataType: "String" },
      { field: "hire_date", description: "The date when the employee was hired.", dataType: "Date" },
      { field: "salary", description: "The employee's base salary.", dataType: "Number" },
      { field: "manager_id", description: "Reference to the employee's manager.", dataType: "String" },
      { field: "email", description: "The employee's work email address.", dataType: "String" },
      { field: "phone", description: "The employee's work phone number.", dataType: "String" },
      { field: "address", description: "The employee's home address.", dataType: "String" },
      { field: "emergency_contact", description: "Name and phone number for emergencies.", dataType: "String" },
      { field: "is_active", description: "Whether the employee is currently employed.", dataType: "Boolean" },
    ],
  }
  
  // Dummy data for each table
  export const dummyData = {
    supermarket_sales: [
      {
        invoice_id: "INV-1001",
        branch: "Branch A",
        city: "New York",
        customer_type: "Member",
        gender: "Female",
        product_line: "Food & Beverages",
        unit_price: 12.99,
        quantity: 3,
        tax: 1.17,
        total: 40.14,
        date: "2023-05-15",
        time: "14:32:00",
        payment: "Credit Card",
        cogs: 32.47,
        gross_margin_percentage: 19.1,
        gross_income: 7.67,
        rating: 8.5,
      },
      {
        invoice_id: "INV-1002",
        branch: "Branch B",
        city: "Los Angeles",
        customer_type: "Normal",
        gender: "Male",
        product_line: "Electronics",
        unit_price: 249.99,
        quantity: 1,
        tax: 22.5,
        total: 272.49,
        date: "2023-05-15",
        time: "15:45:00",
        payment: "E-wallet",
        cogs: 199.99,
        gross_margin_percentage: 20.0,
        gross_income: 50.0,
        rating: 7.8,
      },
    ],
  
    products: [
      {
        product_id: "P-1001",
        product_name: "Organic Bananas",
        category: "Food & Beverages",
        sub_category: "Fruits",
        brand: "Nature's Best",
        retail_price: 1.99,
        wholesale_price: 0.89,
        stock_quantity: 150,
        reorder_level: 30,
        expiry_date: "2023-06-10",
        supplier_id: "SUP-101",
        is_active: true,
      },
      {
        product_id: "P-1002",
        product_name: "Wireless Bluetooth Headphones",
        category: "Electronics",
        sub_category: "Audio",
        brand: "SoundMax",
        retail_price: 79.99,
        wholesale_price: 45.5,
        stock_quantity: 25,
        reorder_level: 5,
        expiry_date: null,
        supplier_id: "SUP-203",
        is_active: true,
      },
    ],
  
    customers: [
      {
        customer_id: "C-1001",
        first_name: "Sarah",
        last_name: "Johnson",
        email: "sarah.j@example.com",
        phone: "212-555-1234",
        address: "123 Main St",
        city: "New York",
        state: "NY",
        zip_code: "10001",
        membership_type: "Gold",
        join_date: "2020-03-15",
        points: 2450,
        birth_date: "1985-07-22",
      },
      {
        customer_id: "C-1002",
        first_name: "Michael",
        last_name: "Brown",
        email: "michael.b@example.com",
        phone: "323-555-6789",
        address: "456 Oak Ave",
        city: "Los Angeles",
        state: "CA",
        zip_code: "90001",
        membership_type: "Silver",
        join_date: "2021-08-10",
        points: 980,
        birth_date: "1990-11-05",
      },
    ],
  
    employees: [
      {
        employee_id: "E-1001",
        first_name: "John",
        last_name: "Smith",
        position: "Store Manager",
        department: "Management",
        branch_id: "Branch A",
        hire_date: "2018-05-10",
        salary: 65000,
        manager_id: null,
        email: "john.smith@company.com",
        phone: "212-555-0101",
        address: "789 Pine St, New York, NY 10002",
        emergency_contact: "Mary Smith, 212-555-0102",
        is_active: true,
      },
      {
        employee_id: "E-1002",
        first_name: "Lisa",
        last_name: "Wong",
        position: "Cashier",
        department: "Sales",
        branch_id: "Branch A",
        hire_date: "2021-02-15",
        salary: 32000,
        manager_id: "E-1001",
        email: "lisa.wong@company.com",
        phone: "212-555-0103",
        address: "101 Maple Ave, New York, NY 10003",
        emergency_contact: "David Wong, 212-555-0104",
        is_active: true,
      },
    ],
  }
  